default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/<%= Rails.env || 'development' %>.sqlite3

development:
  <<: *default

test:
  <<: *default
  database: db/test.sqlite3

production:
  adapter: postgresql
  encoding: unicode
  pool:     50
  timeout:  5000
  database: <%= ENV.fetch('DB_NAME',     'webapp') %>
  username: <%= ENV.fetch('DB_USERNAME', 'webapp')  %>
  password: <%= ENV.fetch('DB_PASSWORD', 'Password1')  %>
  host:     localhost
  port:     5432
